spring.application.name=ApiGatewayService
server.port=8765

#Logs
logging.level.root=INFO
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){blue} %clr(%-5level){yellow} %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %clr(%msg){green}%n

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
spring.cloud.loadbalancer.cache.enabled=false

#JWT
jwt.secret=${JWT_SECRET}

